version: '3.3'

services:

  database:
    image: {DTR_HOST}/dockersamples/hybrid-app-db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
    - published: 3306
      target: 3306
    networks:
    - back-tier

  java-app:
    image: {DTR_HOST}/dockersamples/hybrid-app-web:v1
    ports:
    - published: 8000
      target: 8000
    - published: 8080
      target: 8080
    networks:
    - back-tier
    - front-tier

networks:
  back-tier:
  front-tier: 